### ISSUE TITLE
PDF has johndoe in the footer

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#27] opened 2021-07-10 11:07 UTC
![image](https://user-images.githubusercontent.com/43353831/125160940-dd86c980-e155-11eb-9b16-adae80281736.png)

**Comment by rikhuijzer** [comment] 2021-07-10 11:41
This is not a bug. It's a documented configuration setting: <https://rikhuijzer.github.io/Books.jl/metadata.html>

Fixed in bf28f1bee2c6e9554783510c4408f4146ce9fef4.

**Closed by rikhuijzer** 2021-07-10 11:41 UTC
Labels: bug
